# Generated by Django 5.2.15 on 2026-06-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type', models.CharField(choices=[('cafe', 'Café'), ('thela', 'Thela / Cart'), ('garden', 'Garden / Park'), ('restaurant', 'Restaurant'), ('shop', 'Shop'), ('shortcut', 'Shortcut / Spot'), ('other', 'Other')], default='other', max_length=20)),
                ('is_on_google', models.BooleanField(default=False, verbose_name='Listed on Google?')),
                ('sector', models.CharField(blank=True, help_text='e.g. Sector 3', max_length=60)),
                ('location_text', models.CharField(blank=True, help_text='Human directions: "footpath near 27th Main"', max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timings_text', models.CharField(blank=True, help_text='e.g. "evenings only", "9am-11pm"', max_length=150)),
                ('price_text', models.CharField(blank=True, help_text='e.g. "Rs 30", "Rs 500 for two", "free"', max_length=100)),
                ('vibe_tag', models.CharField(blank=True, choices=[('worth_the_detour', 'Worth the detour'), ('only_if_nearby', 'Only if nearby'), ('calm_o_meter_max', 'Calm-o-meter: max'), ('hidden_gem', 'Hidden gem'), ('local_favourite', 'Local favourite')], max_length=30)),
                ('caption', models.TextField(help_text='Main review / write-up')),
                ('practical_notes', models.CharField(blank=True, help_text='"cash only", "sells out by 9"', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Handwritten-style aside', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
